### ISSUE TITLE
The function Classifier.predict loss the lasest argument 'emb_name' in classifier.py (line 58) called by process in process.py (line 191)

### ISSUE THREAD

**Issue by hulian9** [hangyu98/IMSP#1]
The function Classifier.predict loss the lasest argument 'emb_name' in classifier.py (line 58) called by process in process.py (line 191)

The terminal infomation is:

(test123) H:\IMSP-master>python main.py
E:\Anaconda3\envs\test123\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_core_web_sm' (2.0.0) requires spaCy v2.0 and is incompatible with the current spaCy version (2
.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more deta
ils and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
args received:  Namespace(build_network=False, eval_iter=30, evaluate=False, other_pred=False, pred_iter=5)
NetworkX network already built
In establishing training network
Removed edges found, now establishing evaluation network
In loading training data
Sampling negatives
size of all negatives:  56738
size of known negatives:  118
size of unknown negatives:  56620
In loading test data
Predicting
In training MLP classifier
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 43, in main
    model_pred(original_G_path=original_G_path, content_emb_path=content_emb_path, model_iter=pred_iter)
  File "H:\IMSP-master\process.py", line 29, in model_pred
    content_emb_path=content_emb_path, classifier='MLP', pred=True, model_iter=model_iter, re_build_g=False)
  File "H:\IMSP-master\process.py", line 191, in process
    index2pair_dict=index2pair_dict, binding=binding, last_iter=False)
TypeError: predict() missing 1 required positional argument: 'emb_name'

How to resolove this bug?How to fix the argument 'emb_name' in this function?Thank you for your reply.

**Comment by hangyu98** [comment]
Please try to install spacy package following instructions in this link: https://spacy.io/models/en
